name: generate animation

on:
  schedule:
    - cron: "*/5 * * * *" # every 6 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: finfin
          svg_out_path: dist/github-contribution-grid-snake.svg
